[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
tun = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }

protocol = { path = "../protocol" }
