[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = {workspace = true}
aes-gcm = { workspace = true }
bincode = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }